syntax = "proto3";
package product;

option go_package = "product/proto";

service ProductService {
  rpc GetProduct(GetProductRequest) returns (Product) {}
  rpc UpdateProduct(Product) returns (Product) {}
}

message GetProductRequest {
  uint64 id = 1;
}

message Product {
  uint64 id = 1;
  string name = 2;
  float price = 3;
  uint64 inventory = 4;
  string description = 5;
  repeated string images = 6;
  string stripe_price_id = 7;
  string stripe_product_id = 8;
  uint64 merchant_id = 9;
} 